service: one-piece-chapter-checker

frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-bundle
  - serverless-offline-scheduler

package:
  individually: true

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - ${file(iam/ssm-iam.yml):SystemManagerIAM}

functions:
  checkManga:
    handler: src/handlers/check-manga-list.handler
    events:
      # Invoke Lambda function every 2 days @ 18:00:00 from Wed, Thu, Fri
      - schedule:
          rate: cron(0 18 ? * WED,THU,FRI *)
          enabled: true

    environment:
      SEND_GRID_TEMPLATE_ID: d-eeda09e5b5654add88b6550083628448
      PARAMETER_NAME_CHAPTER_NO: one-piece-last-known-chapter-no
      PARAMETER_NAME_SENDGRID_API_KEY: send-grid-api-key

custom:
  bundle:
    sourcemaps: false
    forceExclude:
      - aws-sdk
